[package]
name = "brute_force_collision"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "brute_force_collision"
path = "src/bin/brute_force_collision.rs"

[dependencies]
rand = "0.8"
num_cpus = "1.0"
